In [4]:
# load the dataset
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('../data/cleaned_career_data.csv')
df.head()

job_title experience_level employment_type  salary  \
0        Data Analyst               EN              FT   75000   
1        Data Analyst               EN              FT   60000   
2  Analytics Engineer               MI              FT  185700   
3  Analytics Engineer               MI              FT  165000   
4       Data Engineer               SE              FT  160000   

  company_location  num_skills  is_data_scientist  is_developer  is_analyst  \
0               US           9                  0             0           0   
1               US           6                  0             0           0   
2               US           7                  0             0           0   
3               US           9                  0             0           0   
4               US           5                  0             0           0   

    interst_area burnout_risk  
0     healthcare          low  
1  cybersecurity          low  
2         webdev       medium  
3        finance          low  
4  cybersecurity          low

feature uesd ---> num_skill, experience_level
target ---> job_title

In [7]:
df = df[['num_skills', 'experience_level', 'job_title']].dropna()

#map experience_leve to number
experience_map = {
    'EN':0,
    'MI': 1,
    'SE': 2,
    'EX': 3
}

df['experience_num']= df['experience_level'].map(experience_map)

In [8]:
# encode job title to number
le = LabelEncoder()
df['job_label'] = le.fit_transform(df['job_title'])


In [21]:
#define features and target
x = df[['num_skills', 'experience_num']]  
y = df['job_label']
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

model = LogisticRegression(class_weight='balanced', max_iter=3000)

model.fit(x_train, y_train)

#predict , evluate
y_pred = model.predict(x_test)
labels_in_test = np.unique(y_test)
class_names_in_test = le.inverse_transform(labels_in_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred, labels=labels_in_test))
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, zero_division=0))






Accuracy: 0.0016611295681063123

Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        14
           5       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         3
           8       0.00      0.00      0.00         5
           9       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         4
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         4
          15       0.00      0.00      0.00         1
          16     

In [22]:
#predict on new data
new_input = pd.DataFrame({'num_skills': [7], 'experience_num': [2]})
pred = model.predict(new_input.values)
predicted_job = le.inverse_transform(pred)[0]
print("Predicted Job Title:", predicted_job)


Predicted Job Title: Deep Learning Researcher
